version: "3.3"

services:
  playbook:
    build: .
    command: >
      sh -c "if [ ! -f /app/ran_once ]; then
               python init_db.py &&
               touch /app/ran_once
             fi &&
             gunicorn --ssl-version TLSv1_2 --certfile /app/certs/cert.crt --keyfile /app/certs/cert.key -b 0.0.0.0:8000 -w 4 wsgi:app"
    restart: always
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_URL
      - POSTGRES_PASSWORD
      - SECRET_KEY
    volumes:
      - ./logs:/app/logs:z
      - ./certs:/app/certs
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

  postgres:
    image: postgres:13
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - ./.env.dev
    # ports:
    #   - "5432:5432"